### ISSUE TITLE
Use not supported, actix library

### ISSUE THREAD

**Issue by greenpdx** [OUISRC/muro#2]
I am using Ubuntu 18.04. with rustc version 1.24.1Do I have to us nighty?
error: nested groups in `use` are experimental (see issue #44494)
  --> src/main.rs:23:30
   |
23 | use actix_web::{server, App, http::{header, Method}, fs, middleware, middleware::cors::Cors};
   |                              ^^^^^^^^^^^^^^^^^^^^^^

error: paths in `use` groups are experimental (see issue #44494)
  --> src/main.rs:23:70
   |
23 | use actix_web::{server, App, http::{header, Method}, fs, middleware, middleware::cors::Cors};
   |                                                                      ^^^^^^^^^^^^^^^^^^^^^^

error: paths in `use` groups are experimental (see issue #44494)
 --> src/api/index.rs:2:17
  |
2 | use actix_web::{fs::NamedFile, HttpRequest, Result};
  |                 ^^^^^^^^^^^^^

error: aborting due to 3 previous errors

error: Could not compile `muro`.

I think this project is great. I used parity json_rpc server to do something similar. Check my within.

**Comment by greenpdx** [comment]
If I move the includes to a separate line it does compile

**Comment by zoltanmaric** [comment]
I managed to resolve this by installing [rust 1.27 beta](https://www.rust-lang.org/en-US/other-installers.html)
